"""
frequency_features.py — Frequency-domain feature extraction for TruPhoto

WHY FREQUENCY FEATURES?
-----------------------
The current CNN pipeline (Xception / MobileNetV2) captures semantic content:
what is in the image. A face photo and a landscape photo produce completely
different CNN feature vectors even if both were generated by the same GAN.

Frequency features capture HOW the image was made. GAN upsampling operations
(transposed convolutions, nearest-neighbor, bilinear) introduce characteristic
periodic artifacts in both the Fourier and DCT domains that are:
  - Content-invariant: the same generator leaves the same spectral fingerprint
    regardless of what is depicted.
  - Persistent across spatial locations: they repeat uniformly, so averaging
    across the image amplifies the signal.
  - Invisible to the human eye but measurable in frequency space.

Two complementary paths, each grounded in a specific paper:

PATH A  — FFT radial power spectrum + power-law decay  (Dzanic et al., NeurIPS 2020)
  Natural images follow a 1/f^alpha power-law decay of Fourier magnitude with
  frequency (well-established in vision science). GAN/diffusion images deviate
  from this decay: their high-frequency bins are boosted by upsampling artifacts
  and their low-frequency bins are shaped by the loss function. Dzanic et al.
  showed that fitting b1, b2 to P(k) = b1 * k^(-b2) gives two parameters that
  linearly separate real from generated images at 99%+ accuracy.
  We keep BOTH the full 100-bin radial spectrum (for the classifier's fine-grained
  view) AND the two fitted decay parameters (the paper's core finding): 102-d total.

PATH B  — Block-level DCT coefficient distribution  (Frank et al., ICML 2020)
  Computed per non-overlapping 8×8 block (JPEG-style). For each of the 63 AC
  coefficient positions (excluding the DC term which only captures mean brightness),
  Frank et al. compute statistics across all blocks in the image. They found that
  GAN upsampling creates consistent elevation or suppression of specific AC
  coefficients that differs from real images. We extract both the mean and the
  standard deviation of each AC coefficient across all blocks, giving the classifier
  information about both the typical amplitude and the spatial consistency of each
  frequency component: 63 × 2 = 126-d total.

COMBINED OUTPUT
  102 (FFT) + 126 (DCT) = 228 dimensions

PUBLIC API
  extract_frequency_features(image_path, n_fft_bins=100, dct_block_size=8)
    → numpy float32 array, shape (228,)

DEPENDENCIES
  numpy   — FFT, radial binning, polyfit
  scipy   — 2D-DCT (dctn)
  PIL     — image loading / grayscale conversion
  All three are already in requirements.txt. No torch, no GPU.
"""

import numpy as np
from PIL import Image
from scipy.fft import dctn


# ============================================================================
# IMAGE LOADING
# ============================================================================

def _load_grayscale(image_path, size=299):
    """
    Load an image, resize it to (size x size), and convert to grayscale.

    We use the standard Rec. 601 luminance weights (the same formula JPEG
    uses internally) rather than a simple channel average, because the
    luminance channel carries the spatial frequency information most
    relevant to forgery detection.

    IMPORTANT: We do NOT apply ImageNet mean/std normalization here.
    Normalization would shift and scale all pixel values by dataset-level
    constants, which would distort the power spectrum in a way that mixes
    up the generator's frequency signature with the dataset's brightness
    distribution. Frequency analysis needs raw pixel intensities.

    Args:
        image_path: path to any PIL-readable image file.
        size:       output spatial dimension (default 299 to match step1).

    Returns:
        gray: float32 numpy array of shape (size, size),
              values in the range [0, 255].
    """
    # Open in RGB mode so we always have three channels, even for grayscale
    # source images (which PIL would otherwise give us a single channel).
    img = Image.open(image_path).convert("RGB")

    # Resize to match the 299x299 images produced by step1
    img = img.resize((size, size), Image.BILINEAR)

    # Split into channels and compute luminance
    r_channel, g_channel, b_channel = img.split()

    r = np.array(r_channel, dtype=np.float32)
    g = np.array(g_channel, dtype=np.float32)
    b = np.array(b_channel, dtype=np.float32)

    # Rec. 601 luminance: same weights JPEG uses, so this is the natural
    # frequency space for JPEG-based frequency analysis.
    gray = 0.299 * r + 0.587 * g + 0.114 * b   # shape: (299, 299)

    return gray


# ============================================================================
# FFT PATH — Dzanic et al., NeurIPS 2020
# ============================================================================

def _build_radius_map(height, width):
    """
    Pre-compute the distance from the image center for every pixel.

    This is the same for every image of the same size, so computing it once
    and reusing it for every image would be ideal in a batched setting.
    Here we compute it fresh per call since step2 is already I/O-bound.

    After fftshift the zero-frequency (DC) component sits at the center
    pixel (cy, cx). The radius of each pixel in this shifted spectrum is
    its distance from that center — which corresponds to its spatial
    frequency magnitude.

    Returns:
        radius_map: float32 array of shape (height, width).
    """
    cy = height // 2     # center row after fftshift
    cx = width  // 2     # center col after fftshift

    # Build offset grids: how far each pixel is from the center
    row_offsets = np.arange(height) - cy     # shape: (height,)
    col_offsets = np.arange(width)  - cx     # shape: (width,)

    # meshgrid gives us 2D grids of offsets for every pixel
    col_grid, row_grid = np.meshgrid(col_offsets, row_offsets)

    # Euclidean distance from the center
    radius_map = np.sqrt(row_grid ** 2 + col_grid ** 2)  # shape: (H, W)

    return radius_map.astype(np.float32)


def _azimuthal_average(magnitude, radius_map, n_bins):
    """
    Average the FFT magnitude spectrum azimuthally (i.e., in radial rings).

    This converts the 2D magnitude spectrum into a 1D radial power spectrum
    P(k), where k indexes spatial frequency and P(k) is the average magnitude
    at that frequency. This is the key step in the Dzanic et al. pipeline.

    Args:
        magnitude:  2D float array — FFT magnitude after fftshift, shape (H, W).
        radius_map: 2D float array — precomputed distance from center, (H, W).
        n_bins:     how many radial frequency bins to divide the spectrum into.

    Returns:
        radial_spectrum: float32 array of shape (n_bins,).
                         Entry i is the average FFT magnitude in the i-th
                         radial frequency band.
    """
    max_radius = radius_map.max()

    # Divide the range [0, max_radius] into n_bins equal-width intervals
    bin_edges = np.linspace(0.0, max_radius, n_bins + 1)

    radial_spectrum = np.zeros(n_bins, dtype=np.float32)

    for i in range(n_bins):
        lower = bin_edges[i]
        upper = bin_edges[i + 1]

        # Select all pixels whose radius falls in this frequency band
        in_bin = (radius_map >= lower) & (radius_map < upper)

        if in_bin.any():
            # Average the magnitude values of all pixels in this band
            radial_spectrum[i] = magnitude[in_bin].mean()
        # else: leave as 0.0 (can happen at very high radii near image corners)

    return radial_spectrum


def _fit_power_law(radial_spectrum):
    """
    Fit P(k) = b1 * k^(-b2) to the radial power spectrum.

    This is the Dzanic et al. core operation. Natural images follow a 1/f
    power-law where P(k) decays as frequency k increases. In log-log space
    this is a straight line:

        log(P(k)) = log(b1) - b2 * log(k)

    So we do a linear regression of log(P) on log(k), which gives:
        - slope     = -b2   (the decay rate)
        - intercept = log(b1)  (the log-magnitude at k=1)

    b2 encodes how quickly the spectrum falls off — real images have a
    steeper, more consistent decay than GAN images whose high frequencies
    are contaminated by upsampling artifacts.

    b1 encodes the overall energy level of the spectrum.

    Args:
        radial_spectrum: 1D float array of shape (n_bins,) from _azimuthal_average.
                         Entry 0 is the DC bin (k=0), entries 1... are AC bins.

    Returns:
        b1: float — power-law magnitude parameter.
        b2: float — power-law decay-rate parameter.
             Returns (0.0, 0.0) if the fit fails (e.g., all-zero spectrum).
    """
    n_bins = len(radial_spectrum)

    # Exclude bin 0 (DC component, log(0) is undefined) and the outermost
    # bins (high radii that correspond to the image corners have very few
    # pixels in each bin, making the estimate noisy).
    start_bin = 1
    end_bin   = max(start_bin + 5, n_bins - 5)   # keep at least a few points

    k_values = np.arange(start_bin, end_bin, dtype=np.float64)
    P_values = radial_spectrum[start_bin:end_bin].astype(np.float64)

    # Remove any zero or negative magnitudes before taking the log
    valid_mask = P_values > 0.0
    if valid_mask.sum() < 5:
        # Not enough valid points — return neutral values
        return 0.0, 0.0

    log_k = np.log(k_values[valid_mask])
    log_P = np.log(P_values[valid_mask])

    # Linear regression: log(P) = log(b1) - b2 * log(k)
    # np.polyfit returns [slope, intercept] for degree-1 polynomial
    coeffs = np.polyfit(log_k, log_P, 1)

    slope     = coeffs[0]   # = -b2
    intercept = coeffs[1]   # = log(b1)

    b2 = float(-slope)             # decay rate (positive for real images)
    b1 = float(np.exp(intercept))  # amplitude

    return b1, b2


def extract_fft_features(gray, n_bins=100):
    """
    Extract FFT-based frequency features following Dzanic et al. (NeurIPS 2020).

    Pipeline:
      grayscale image
        → 2D FFT → shift DC to center → magnitude spectrum
        → azimuthal average → 100-bin radial power spectrum
        → log1p compression (keeps scale manageable)
        → fit power-law decay → b1, b2
        → concatenate [spectrum (100-d), b1, b2] → 102-d vector

    The radial spectrum gives the classifier 100 frequency channels to work
    with. The decay parameters b1 and b2 give it the two numbers that
    Dzanic et al. showed are most discriminative.

    Args:
        gray:   float32 array of shape (H, W), pixel values in [0, 255].
        n_bins: number of radial frequency bins (default 100).

    Returns:
        features: float32 array of shape (n_bins + 2,) = (102,).
    """
    # Step 1: 2D Fast Fourier Transform
    # Output is a complex array of shape (H, W)
    fft_complex = np.fft.fft2(gray)

    # Step 2: Shift so that the zero-frequency (DC) component is at the center
    # Without this, DC is at corner (0,0) and radius calculations don't work
    fft_shifted = np.fft.fftshift(fft_complex)

    # Step 3: Take the magnitude of the complex spectrum
    # We discard the phase — generator artifacts show up in the magnitude,
    # not in the phase structure of individual images
    magnitude = np.abs(fft_shifted)   # shape: (H, W), all non-negative

    # Step 4: Build the radius map and compute the azimuthal average
    h, w = magnitude.shape
    radius_map = _build_radius_map(h, w)
    radial_spectrum = _azimuthal_average(magnitude, radius_map, n_bins)  # (100,)

    # Step 5: Log-scale compression
    # Raw FFT magnitudes span many orders of magnitude: the DC bin can be
    # 10,000x larger than the high-frequency bins. log1p brings them into
    # a similar range so the classifier doesn't ignore high-frequency signals.
    spectrum_log = np.log1p(radial_spectrum)   # (100,)

    # Step 6: Fit the power-law decay curve P(k) = b1 * k^(-b2)
    # These two parameters are Dzanic et al.'s primary discriminative features.
    # We fit on the pre-log spectrum so the parameters have their natural meaning.
    b1, b2 = _fit_power_law(radial_spectrum)

    # Step 7: Concatenate spectrum + decay parameters
    decay_params = np.array([b1, b2], dtype=np.float32)
    features = np.concatenate([spectrum_log, decay_params])   # (102,)

    return features.astype(np.float32)


# ============================================================================
# DCT PATH — Frank et al., ICML 2020
# ============================================================================

def extract_dct_features(gray, block_size=8):
    """
    Extract block-DCT coefficient distribution statistics following Frank et al.
    (ICML 2020).

    Pipeline:
      grayscale image
        → divide into non-overlapping 8x8 blocks  (JPEG-style)
        → 2D-DCT per block (orthonormal normalization)
        → for each of the 63 AC coefficient positions:
              collect the value from every block → distribution
              compute mean + standard deviation of that distribution
        → concatenate [63 means, 63 stds] → 126-d vector

    WHY BLOCKS?
    GAN upsampling artifacts are periodic across the image — they repeat
    at the same spatial frequency everywhere. By computing the DCT per
    8x8 block and then AVERAGING the coefficients across all blocks, we
    amplify this periodic pattern while averaging out image content
    (which varies block to block). This is exactly why the DCT basis
    is chosen: it concentrates periodic energy into specific coefficients.

    WHY MEAN + STD?
    The mean captures the average amplitude of each frequency component
    across the image. The standard deviation captures how consistent that
    amplitude is across spatial locations. Real photos have natural
    content variation (high std), while GAN images with periodic artifacts
    tend to have more uniform frequency distributions (lower std). Frank
    et al. found both statistics discriminative.

    WHY DROP THE DC COEFFICIENT?
    The DC coefficient at position [0,0] captures the mean luminance of
    each block. It varies with overall image brightness, which tells us
    nothing about whether the image was generated. Keeping it would add
    noise to the feature vector.

    Args:
        gray:       float32 array of shape (H, W), values in [0, 255].
        block_size: tile size for the block DCT (default 8 = JPEG-style).

    Returns:
        features: float32 array of shape (2 * (block_size^2 - 1),) = (126,).
                  First 63 entries are per-coefficient means,
                  last  63 entries are per-coefficient standard deviations.
    """
    h, w = gray.shape

    # How many complete blocks fit in each dimension
    n_blocks_h = h // block_size   # = 37 for 299x299 with block_size=8
    n_blocks_w = w // block_size   # = 37

    n_coeff = block_size * block_size   # = 64 coefficients per block

    # Accumulate all blocks' DCT coefficients so we can compute
    # statistics across the block population at the end.
    # Shape: (n_blocks_h * n_blocks_w, n_coeff) = (1369, 64)
    # We'll fill this row by row as we iterate through blocks.
    total_blocks = n_blocks_h * n_blocks_w
    all_coeffs = np.zeros((total_blocks, n_coeff), dtype=np.float32)

    block_idx = 0

    for row in range(n_blocks_h):
        for col in range(n_blocks_w):

            # Extract the (row, col)-th block from the image
            r_start = row * block_size
            c_start = col * block_size
            block = gray[r_start : r_start + block_size,
                         c_start : c_start + block_size]

            # 2D Discrete Cosine Transform with orthonormal normalization.
            # norm='ortho' makes the transform energy-preserving, which
            # allows fair comparison of coefficient amplitudes across blocks
            # of different mean luminance — consistent with Frank et al.
            dct_block = dctn(block, norm="ortho")   # shape: (block_size, block_size)

            # Flatten to 1D and store in the accumulation matrix
            all_coeffs[block_idx] = dct_block.flatten()   # (64,)

            block_idx += 1

    # all_coeffs is now (1369, 64) — each row is one block's 64 coefficients

    # Compute statistics ACROSS blocks for each coefficient POSITION.
    # axis=0 means we collapse the block dimension: result is (64,).
    coeff_mean = all_coeffs.mean(axis=0)   # (64,) — mean across all 1369 blocks
    coeff_std  = all_coeffs.std(axis=0)    # (64,) — std  across all 1369 blocks

    # Drop the DC term (index 0) from both statistics.
    # The DC coefficient is the block mean — it captures brightness,
    # not frequency structure, so it adds noise rather than signal.
    ac_mean = coeff_mean[1:]   # (63,)
    ac_std  = coeff_std[1:]    # (63,)

    # Concatenate mean and std into a single feature vector
    features = np.concatenate([ac_mean, ac_std])   # (126,)

    return features.astype(np.float32)


# ============================================================================
# PUBLIC API
# ============================================================================

def extract_frequency_features_from_array(gray, n_fft_bins=100, dct_block_size=8):
    """
    Same as extract_frequency_features but accepts a pre-loaded grayscale
    float32 numpy array of shape (H, W) with values in [0, 255].

    Used by step5_gradio_demo where the image arrives as a PIL object
    rather than a file path.
    """
    fft_features = extract_fft_features(gray, n_bins=n_fft_bins)
    dct_features = extract_dct_features(gray, block_size=dct_block_size)
    return np.concatenate([fft_features, dct_features]).astype(np.float32)


def extract_frequency_features(image_path, n_fft_bins=100, dct_block_size=8):
    """
    Extract a combined frequency-domain feature vector from a single image.

    This is the only function step2_extract_features.py calls.

    Combines:
      FFT path  (Dzanic et al., NeurIPS 2020):
        - 100-bin azimuthally-averaged log radial power spectrum
        -   2 power-law decay parameters (b1, b2)
        = 102 dimensions

      DCT path  (Frank et al., ICML 2020):
        - 63 AC coefficient means  across 8x8 blocks
        - 63 AC coefficient stds   across 8x8 blocks
        = 126 dimensions

      Total: 228 dimensions.

    CONTENT INVARIANCE
    A face photo and a landscape photo generated by the same GAN will have
    similar frequency feature vectors, because the upsampling artifacts that
    both feature paths detect are imposed by the generator architecture, not
    by the image content. Real photos from either scene will share the natural
    power-law decay and natural DCT statistics. This is the key property that
    makes frequency features complementary to CNN features.

    Args:
        image_path:     path to a JPEG/PNG image file.
                        The image will be internally resized to 299×299 to
                        match the images produced by step1.
        n_fft_bins:     number of radial bins for the FFT spectrum (default 100).
        dct_block_size: tile size for block DCT (default 8, JPEG-style).

    Returns:
        features: float32 numpy array of shape (228,) with default arguments.
                  Indices   0 – 99:  FFT radial spectrum (log-compressed)
                  Indices 100 – 101: FFT decay params b1, b2
                  Indices 102 – 164: DCT AC coefficient means
                  Indices 165 – 227: DCT AC coefficient stds
    """
    np.random.seed(42)   # ensures reproducibility if any stochastic step is added later

    # --- Step 1: Load and convert to grayscale ---
    # Both paths operate on luminance; computing grayscale once and reusing
    # it avoids loading the image twice.
    gray = _load_grayscale(image_path)

    # --- Step 2: FFT path (Dzanic et al.) ---
    # 100-bin radial power spectrum + 2 decay parameters = 102-d
    fft_features = extract_fft_features(gray, n_bins=n_fft_bins)   # (102,)

    # --- Step 3: DCT path (Frank et al.) ---
    # Mean + std of 63 AC DCT coefficients = 126-d
    dct_features = extract_dct_features(gray, block_size=dct_block_size)   # (126,)

    # --- Step 4: Concatenate ---
    combined = np.concatenate([fft_features, dct_features])   # (228,)

    return combined.astype(np.float32)
